---
- name: apache tomcat
  hosts: apache
  sudo: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
      become: yes
    - name: ensure apache is  running
      service: name=apache2 state=started
