---
- name: Copy
  hosts: apache
  sudo: yes
  tasks:
    - name: example copying file with owner and permissions
      copy:
        src: /etc/ansible/blueegreen/index.html
        dest: /var/www/html/index.html
        owner: ansible
